/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    'IMdi:check': typeof import('~icons/mdi/check')['default']
    'IMdi:chevronLeft': typeof import('~icons/mdi/chevron-left')['default']
    'IMdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
